In [1]:
import numpy as np

In [2]:
a = np.array([[[10,20,30,40],[50,60,70,80]],[[10,20,30,40],[50,60,70,80]]])
a

array([[[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [3]:
print(a.ndim)

3


In [4]:
a.shape

(2, 2, 4)

In [5]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [6]:
m[1,2]

7

In [7]:
m[-1,-1]

14

In [8]:

m[1,1:3]

array([6, 7])

In [9]:
m[1:,2]

array([ 7, 12])

In [10]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

In [11]:
m[0:2, -1:-3:-1]

array([[4, 3],
       [9, 8]])

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [14]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [15]:
y=x[(x%3==0) & (x%4==1)]
y


array([9])

In [16]:
a = np.array([[0,0,0,1,1],[0,0,0,1,1],[0,0,0,1,1]]).astype(float)
b= np.arange(10,160,10).reshape(3,5).astype(float)
c=np.vstack([a,b])
np.vstack([c,c])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [17]:
import random
a=np.random.rand(30).reshape(5,6)
a

array([[0.05990257, 0.490885  , 0.01283166, 0.61020523, 0.98536736,
        0.61393737],
       [0.17936362, 0.54242189, 0.74389048, 0.26498465, 0.0713092 ,
        0.63627827],
       [0.66621767, 0.25579348, 0.96459243, 0.07925978, 0.46046425,
        0.6411354 ],
       [0.46531713, 0.31570537, 0.83255572, 0.01341929, 0.40724771,
        0.96186038],
       [0.540133  , 0.78919399, 0.63083403, 0.17104636, 0.10318193,
        0.73175469]])

In [18]:
a.max()

0.9853673613478744

In [19]:
a.sum(axis=1)

array([2.77312919, 2.4382481 , 3.067463  , 2.99610561, 2.966144  ])

In [20]:
a.max(axis=1)

array([0.98536736, 0.74389048, 0.96459243, 0.96186038, 0.78919399])

In [21]:
a.mean(axis=0)

array([0.3821868 , 0.47879995, 0.63694086, 0.22778306, 0.40551409,
       0.71699322])

In [22]:
a.min(axis=0)

array([0.05990257, 0.25579348, 0.01283166, 0.01341929, 0.0713092 ,
       0.61393737])

In [23]:
a=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
a.astype(int)

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [24]:
a[1].argsort()

array([0, 3, 1, 2], dtype=int64)

In [25]:
a[0][a[1].argsort()]

array([1, 4, 2, 3])

In [26]:
a[2][a[1].argsort()]

array([ 81, 100,  59,  90])

In [27]:
c = np.array([a[0][a[1].argsort()], a[1], a[2][a[1].argsort()]])
c

array([[  1,   4,   2,   3],
       [ 46,  99, 100,  71],
       [ 81, 100,  59,  90]])

In [28]:

np.random.randint(1,100,10)

array([37, 36, 70, 95, 36, 49, 60, 91, 52, 53])

In [29]:
import random
random.seed(2021)
a = np.random.randint(1,100,10)
for i in a:
  if i % 2 == 0:
    print('1')
  elif i % 2 ==1 :
    print('0')
  
  



0
0
1
0
0
0
1
1
0
0


In [30]:
import random
b=0
for i in range(1,101):
  a = np.random.randint(1,7,1)
  b += a
  print(b/i)


[4.]
[5.]
[3.66666667]
[3.5]
[3.8]
[3.66666667]
[3.57142857]
[3.5]
[3.77777778]
[3.9]
[3.72727273]
[3.66666667]
[3.76923077]
[3.85714286]
[4.]
[3.875]
[4.]
[4.]
[3.94736842]
[3.95]
[4.]
[4.]
[4.04347826]
[4.08333333]
[4.12]
[4.03846154]
[3.92592593]
[3.92857143]
[3.93103448]
[3.93333333]
[3.90322581]
[3.8125]
[3.81818182]
[3.82352941]
[3.88571429]
[3.83333333]
[3.86486486]
[3.84210526]
[3.8974359]
[3.925]
[3.87804878]
[3.80952381]
[3.74418605]
[3.75]
[3.73333333]
[3.69565217]
[3.72340426]
[3.66666667]
[3.69387755]
[3.68]
[3.62745098]
[3.61538462]
[3.64150943]
[3.61111111]
[3.6]
[3.57142857]
[3.52631579]
[3.55172414]
[3.55932203]
[3.55]
[3.50819672]
[3.5]
[3.46031746]
[3.453125]
[3.46153846]
[3.43939394]
[3.44776119]
[3.47058824]
[3.50724638]
[3.5]
[3.53521127]
[3.51388889]
[3.47945205]
[3.48648649]
[3.50666667]
[3.52631579]
[3.50649351]
[3.52564103]
[3.50632911]
[3.525]
[3.55555556]
[3.53658537]
[3.53012048]
[3.55952381]
[3.57647059]
[3.59302326]
[3.56321839]
[3.55681818]
[3.5505618]
[

In [31]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [32]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [33]:
a=iris.target_names



In [34]:
name1=a[0][:3].upper()
name2=a[1][:3].upper()
name3=a[2][:3].upper()


In [35]:
for i in range(3):
  name = a[i][:3].upper()
  print(name)

SET
VER
VIR


In [36]:
a= pd.Series([1,3,4,5,6], index = ('d','f','r','y','q'))
b= pd.Series([2,6,4,0,1], index = ('d','f','c','v','b'))
c=a+b
c[c.notnull()]

d    3.0
f    9.0
dtype: float64

In [37]:
df = pd.DataFrame([[1,'T',4.0,5,6],[2,'d',4.0,5,6],[2,'q',4.0,5,6],[4,'v',6.0,7,8],[0,'j',8.0,7,6]], columns = ['아리가또','땡큐','쒜쒜','감사','쿠텐탁'])
df

아리가또 땡큐   쒜쒜  감사  쿠텐탁
0     1  T  4.0   5    6
1     2  d  4.0   5    6
2     2  q  4.0   5    6
3     4  v  6.0   7    8
4     0  j  8.0   7    6

In [38]:
df.T

0    1    2    3    4
아리가또    1    2    2    4    0
땡큐      T    d    q    v    j
쒜쒜    4.0  4.0  4.0  6.0  8.0
감사      5    5    5    7    7
쿠텐탁     6    6    6    8    6

In [39]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [40]:
df['평균'] = df.mean(axis=1)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

In [41]:
df.loc['방자','영어'] = 80
df['평균'] = df.mean(axis=1)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  56.666667

In [42]:
df['춘향':'춘향']

국어  영어  수학         평균
춘향  80  90  90  86.666667

In [43]:
df.loc['향단',:]

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

In [44]:
import random
import numpy as np
import pandas as pd
a= np.random.randint(1,100,25).reshape(5,5)
df = pd.DataFrame(a, columns=['야바','리','욜','열','헐'], index= ['1','2','3','4','5'])
df

야바   리   욜   열   헐
1  55  58  78  96  62
2  84  11  62  79  66
3  76  33  40  92  54
4  87   3  18  25  56
5  29  74  66  45  17

In [45]:
df['야바'] #1
df.loc['2':,['욜']] #2

욜
2  62
3  40
4  18
5  66

In [46]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [47]:
titanic.groupby('sex').count()


survived  pclass  age  sibsp  parch  fare  embarked  class  who  \
sex                                                                       
female       314     314  261    314    314   314       312    314  314   
male         577     577  453    577    577   577       577    577  577   

        adult_male  deck  embark_town  alive  alone  
sex                                                  
female         314    97          312    314    314  
male           577   106          577    577    577

In [48]:
titanic[titanic.sex == 'female']

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
9           1       2  female  14.0      1      0  30.0708        C  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
880         1       2  female  25.0      0      1  26.0000        S  Second   
882         0       3  female  22.0      0      0  10.5167        S   Third   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
8    woman       False  NaN  Southampton   yes  False  
9    child       False  NaN    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
880  woman       False  NaN  Southampton   yes  False  
882  woman       False  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  

[314 rows x 15 columns]

In [49]:
a=titanic.sort_values(by='sex')
a.loc[:,'sex'].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [50]:
a=titanic.sort_values(by='age').loc[:,'age'].value_counts()
a

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
36.50     1
74.00     1
0.92      1
70.50     1
12.00     1
Name: age, Length: 88, dtype: int64

In [51]:
titanic.age.mean()

29.69911764705882

In [52]:
titanic[titanic.sex=='female'].age.mean()

27.915708812260537

In [53]:
titanic[(titanic.pclass==1) &(titanic.sex=='female')].age.mean()

34.61176470588235

In [54]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [55]:
titanic[titanic.age>20]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
884         0       3    male  25.0      0      0   7.0500        S   Third   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
884    man        True  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
886    man        True  NaN  Southampton    no   True  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[535 rows x 15 columns]

In [56]:
titanic['category1']=titanic.apply(lambda x : x.sex if x.age >20 else 'child', axis=1)
titanic


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1  
0      man        True  NaN  Southampton    no  False      male  
1    woman       False    C    Cherbourg   yes  False    female  
2    woman       False  NaN  Southampton   yes   True    female  
3    woman       False    C  Southampton   yes  False    female  
4      man        True  NaN  Southampton    no   True      male  
..     ...         ...  ...          ...   ...    ...       ...  
886    man        True  NaN  Southampton    no   True      male  
887  woman       False    B  Southampton   yes   True     child  
888  woman       False  NaN  Southampton    no  False     child  
889    man        True    C    Cherbourg   yes   True      male  
890    man        True  NaN   Queenstown    no   True      male  

[891 rows x 16 columns]

In [57]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
category1        0
dtype: int64

In [58]:
df=titanic.age.fillna(titanic.age.mean())
df.isna().sum()

0

In [59]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [60]:
titanic.age.dropna().isna().sum()

0

In [61]:
titanic['category2'] =titanic.sex.astype(str) +titanic.age.astype(str)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1   category2  
0      man        True  NaN  Southampton    no  False      male    male22.0  
1    woman       False    C    Cherbourg   yes  False    female  female38.0  
2    woman       False  NaN  Southampton   yes   True    female  female26.0  
3    woman       False    C  Southampton   yes  False    female  female35.0  
4      man        True  NaN  Southampton    no   True      male    male35.0  
..     ...         ...  ...          ...   ...    ...       ...         ...  
886    man        True  NaN  Southampton    no   True      male    male27.0  
887  woman       False    B  Southampton   yes   True     child  female19.0  
888  woman       False  NaN  Southampton    no  False     child   femalenan  
889    man        True    C    Cherbourg   yes   True      male    male26.0  
890    man        True  NaN   Queenstown    no   True      male    male32.0  

[891 rows x 17 columns]

In [68]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  category1    891 non-null    object  
 16  category2    891 non-null    object  
dtypes: bool(2), category(2), float64(2), int64(4), object(7)
memory usage: 94

In [71]:
titanic.age=titanic.age.astype(str)
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    object  
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
 15  category1    891 non-null    object  
 16  category2    891 non-null    object  
dtypes: bool(2), category(2), float64(1), int64(4), object(8)
memory usage: 94

In [73]:
titanic['a'] = titanic.apply(lambda x : x.sex + x.age, axis=1)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   nan      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1   category2  \
0      man        True  NaN  Southampton    no  False      male    male22.0   
1    woman       False    C    Cherbourg   yes  False    female  female38.0   
2    woman       False  NaN  Southampton   yes   True    female  female26.0   
3    woman       False    C  Southampton   yes  False    female  female35.0   
4      man        True  NaN  Southampton    no   True      male    male35.0   
..     ...         ...  ...          ...   ...    ...       ...         ...   
886    man        True  NaN  Southampton    no   True      male    male27.0   
887  woman       False    B  Southampton   yes   True     child  female19.0   
888  woman       False  NaN  Southampton    no  False     child   femalenan   
889    man        True    C    Cherbourg   yes   True      male    male26.0   
890    man        True  NaN   Queenstown    no   True      male    male32.0   

              a  
0      male22.0  
1    female38.0  
2    female26.0  
3    female35.0  
4      male35.0  
..          ...  
886    male27.0  
887  female19.0  
888   femalenan  
889    male26.0  
890    male32.0  

[891 rows x 18 columns]

In [ ]:
titanic['category2'] = titanic.apply(lambda x : x.sex, axis=1)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1 category2  \
0      man        True  NaN  Southampton    no  False      male      male   
1    woman       False    C    Cherbourg   yes  False    female    female   
2    woman       False  NaN  Southampton   yes   True    female    female   
3    woman       False    C  Southampton   yes  False    female    female   
4      man        True  NaN  Southampton    no   True      male      male   
..     ...         ...  ...          ...   ...    ...       ...       ...   
886    man        True  NaN  Southampton    no   True      male      male   
887  woman       False    B  Southampton   yes   True     child    female   
888  woman       False  NaN  Southampton    no  False     child    female   
889    man        True    C    Cherbourg   yes   True      male      male   
890    man        True  NaN   Queenstown    no   True      male      male   

       구분 category3 category5  
0      청년         s      male  
1      중년         s    female  
2      청년         s    female  
3      중년         s    female  
4      중년         s      male  
..    ...       ...       ...  
886    청년         s      male  
887  미성년자      미성년자    female  
888   NaN         s    female  
889    청년         s      male  
890    중년         s      male  

[891 rows x 20 columns]

In [ ]:
# apply전에 df가 들어가면 x=columns, columns가 들어가면 x=elements
titanic['category2'] = titanic.apply(lambda x : titanic.sex)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1 category2  \
0      man        True  NaN  Southampton    no  False      male      male   
1    woman       False    C    Cherbourg   yes  False    female    female   
2    woman       False  NaN  Southampton   yes   True    female    female   
3    woman       False    C  Southampton   yes  False    female    female   
4      man        True  NaN  Southampton    no   True      male      male   
..     ...         ...  ...          ...   ...    ...       ...       ...   
886    man        True  NaN  Southampton    no   True      male      male   
887  woman       False    B  Southampton   yes   True     child    female   
888  woman       False  NaN  Southampton    no  False     child    female   
889    man        True    C    Cherbourg   yes   True      male      male   
890    man        True  NaN   Queenstown    no   True      male      male   

       구분  
0      청년  
1      중년  
2      청년  
3      중년  
4      중년  
..    ...  
886    청년  
887  미성년자  
888   NaN  
889    청년  
890    중년  

[891 rows x 18 columns]

In [ ]:
bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
pd.cut(titanic.age, bins, labels=labels).to_frame()

age
0      청년
1      중년
2      청년
3      중년
4      중년
..    ...
886    청년
887  미성년자
888   NaN
889    청년
890    중년

[891 rows x 1 columns]

In [ ]:
df = pd.cut(titanic.age, bins, labels=labels)
titanic['구분']= df 
a = titanic.groupby('구분').count()['pclass']
b=a / titanic.구분.count()
sum(b)

1.0

In [ ]:
titanic.drop(columns = ['ratio'], inplace=True)
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone category1   category2  \
0      man        True  NaN  Southampton    no  False      male    male22.0   
1    woman       False    C    Cherbourg   yes  False    female  female38.0   
2    woman       False  NaN  Southampton   yes   True    female  female26.0   
3    woman       False    C  Southampton   yes  False    female  female35.0   
4      man        True  NaN  Southampton    no   True      male    male35.0   
..     ...         ...  ...          ...   ...    ...       ...         ...   
886    man        True  NaN  Southampton    no   True      male    male27.0   
887  woman       False    B  Southampton   yes   True     child  female19.0   
888  woman       False  NaN  Southampton    no  False     child   femalenan   
889    man        True    C    Cherbourg   yes   True      male    male26.0   
890    man        True  NaN   Queenstown    no   True      male    male32.0   

       구분  
0      청년  
1      중년  
2      청년  
3      중년  
4      중년  
..    ...  
886    청년  
887  미성년자  
888   NaN  
889    청년  
890    중년  

[891 rows x 18 columns]

In [ ]:
bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
titanic['category3'] = titanic.apply(lambda x : '미성년자' if x.age <20 else pd.cut(x.age, bins, labels=labels) + x.sex, axis=1)


ValueError: Input array must be 1 dimensional